repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.2
    hooks:
      - id: auto-walrus
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - --quiet-level=2
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.259
    hooks:
      - id: ruff
        args: [--select, "B,E,F,I,S,SIM,UP,W", --ignore, "S101", --target-version, py37]
