name: ci
on: [pull_request, push]
jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install --upgrade pip wheel
      - uses: pre-commit/action@v2.0.3
  mypy_and_pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install --upgrade pip wheel
      - run: pip install mypy pytest safety
      - run: sudo apt-get update ; sudo apt install espeak ffmpeg libespeak1 portaudio19-dev
      - run: pip install -r requirements.txt
      - run: mypy --ignore-missing-imports --install-types --non-interactive --show-error-codes .
      - run: pytest --doctest-modules .
      - run: safety check
