name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - uses: pre-commit/action@v2.0.3
      - run: pip install bandit mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101,B307 .
      - run: sudo apt-get install libespeak-dev portaudio19-dev
      - run: pip install -r requirements.txt
      #- run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive --show-error-codes .
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
